version: "3.4"

services:
    server:
        build:
          context: ./server
          dockerfile: Dockerfile
        ports:
          - "5000:5000"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:5000/api/article"]
          interval: 10s
          timeout: 10s
          retries: 3
          start_period: 10s
    client:
        build:
          context: ./client
          dockerfile: Dockerfile
        ports:
          - "4200:4200"
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:4200"]
          interval: 10s
          timeout: 10s
          retries: 3
          start_period: 10s